site_name: MCP Census Server Documentation
docs_dir: docs
site_dir: site
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    - navigation.tabs
    - content.code.copy
nav:
  - Intro: index.md
  - About: about.md
  - How to Run: howto.md
  - Authentication: authentication.md
  - Usage: usage.md
  - Architecture: architecture.md