name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload docs content
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1